name: Build ARM64 Fan Controller

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-arm64:
    name: Build & push arm64 image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU (for cross-arch builds)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug   # optional for troubleshooting :contentReference[oaicite:1]{index=1}

      - name: Log in to container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push arm64 image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Pkgfile
          platforms: linux/arm64
          target: fan-controller
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/fan-controller:1.0-arm64
